
project_id = "omobmgybzsdhtphvuaav"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://omobmgybzsdhtphvuaav.lovable.app"]
