
project_id = "omobmgybzsdhtphvuaav"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[storage]
enabled = true

[auth]
enabled = true
site_url = "https://omobmgybzsdhtphvuaav.lovable.app"
additional_redirect_urls = [
  "https://omobmgybzsdhtphvuaav.lovable.app", 
  "https://omobmgybzsdhtphvuaav.lovable.app/reset-password", 
  "https://omobmgybzsdhtphvuaav.lovable.app/login"
]
