
project_id = "omobmgybzsdhtphvuaav"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:8080"
additional_redirect_urls = [
  "https://omobmgybzsdhtphvuaav.lovable.app", 
  "https://omobmgybzsdhtphvuaav.lovable.app/reset-password", 
  "https://omobmgybzsdhtphvuaav.lovable.app/login",
  "http://localhost:8080",
  "http://localhost:8080/reset-password",
  "http://localhost:8080/login"
]
