// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omobmgybzsdhtphvuaav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tb2JtZ3lienNkaHRwaHZ1YWF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMjAyMDMsImV4cCI6MjA2Mjc5NjIwM30.4z8rgoTjbHuv7UQ81quEHr3G6BeHv1ooJCOe9o0BBDU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);